name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.19.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and build
        working-directory: ./todo
        run: npm install && npm run build && cp dist/todo/index.html dist/todo/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: todo/dist/todo
